# Generated by Django 4.2.6 on 2023-11-01 19:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_customer_image_name'),
        ('products', '0003_alter_brand_image_name_alter_product_image_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ درج سفارش')),
                ('update_date', models.DateField(auto_now=True, verbose_name='تاریخ ویرایش سفارش')),
                ('is_finaly', models.BooleanField(default=False, verbose_name='نهایی شده')),
                ('order_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='کد تولیدی برای سفارش')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='تخفیف روی فاکتور')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=60, verbose_name='وضعیت سفارش')),
            ],
            options={
                'verbose_name': 'وضعیت سفارش',
                'verbose_name_plural': 'انواع وضعیت\u200cهای سفارش',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_title', models.CharField(max_length=50, verbose_name='نوع پرداخت')),
            ],
            options={
                'verbose_name': 'نوع پرداخت',
                'verbose_name_plural': 'انواع روش پرداخت',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('price', models.IntegerField(verbose_name='قیمت کالا در فاکتور')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_details1', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_details2', to='products.product', verbose_name='کالا')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.orderstatus', verbose_name='وضعیت سفارش'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_types', to='orders.paymenttype', verbose_name='نوع پرداخت'),
        ),
    ]
