# Generated by Django 4.2.6 on 2023-11-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_is_finaly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.AddField(
            model_name='order',
            name='is_finally',
            field=models.BooleanField(default=False, verbose_name='نهایی شده'),
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
