# Generated by Django 4.2.6 on 2023-11-01 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('landline_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن ثابت')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('image_name', models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='تصویر پروفایل')),
            ],
        ),
    ]
