# Generated by Django 4.2.6 on 2023-11-10 17:59

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_customer_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='complete_register',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='تکمیل ثبت نام'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='تصویر پروفایل'),
        ),
    ]
