# Generated by Django 4.2.6 on 2023-11-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='انجام شده'),
        ),
    ]
