# Generated by Django 4.2.6 on 2023-11-05 18:58

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='تصویر مقاله'),
        ),
    ]
