# Generated by Django 4.2.6 on 2023-11-08 11:04

import datetime
from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='تصویر مقاله'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 8, 11, 4, 52, 429650), verbose_name='تاریخ انتشار'),
        ),
    ]
