# Generated by Django 4.2.6 on 2023-11-08 21:53

from django.db import migrations, models
import django.utils.timezone
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blog_image_name_alter_blog_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='تصویر مقاله'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار'),
        ),
    ]
