# Generated by Django 4.2.6 on 2023-11-08 11:04

from django.db import migrations, models
import django.utils.timezone
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_slider_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='publish_datetime',
        ),
        migrations.AddField(
            model_name='slider',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='تصویر اسلاید'),
        ),
    ]
